name: InvlteList
version: '1.0.0'
main: it.mitl.invlteList.InvlteList
api-version: '1.21'
authors: [ Mitlit ]
description: Maintain security and an active community by allowing pre-existing server members to invite other players to the whitelist.
website: dev.mitl.it
